#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require 'vendor/autoload.php';

$app = new Application('Shopping Cart App', '1.0.0');

try
{
    $pdo = new PDO('sqlite:shoppingcart.sqlite');

    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch (Exception $exception)
{
    echo 'Could not connect to the database';
    exit(1);
}

$dbAdapter = new ShoppingCart\DatabaseAdapter($pdo);

$app->add(new \ShoppingCart\Commands\Cart\AddCommand($dbAdapter));
$app->add(new \ShoppingCart\Commands\Cart\CheckoutCommand($dbAdapter));
$app->add(new \ShoppingCart\Commands\Cart\EndCommand($dbAdapter));
$app->add(new \ShoppingCart\Commands\Cart\RemoveCommand($dbAdapter));

$app->run();